<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_model');
    }

    /*
     * Listing of barang
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('barang/index?');
        $config['total_rows'] = $this->Barang_model->get_all_barang_count();
        $this->pagination->initialize($config);

        $data['barang'] = $this->Barang_model->get_all_barang($params);

        $data['title'] = 'Barang';

        $this->load->view('templates/header', $data);
        $this->load->view('templates/navbar', $data);
        $this->load->view('barang/index', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new barang
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('NAMABARANG', 'NAMABARANG', 'required');
        $this->form_validation->set_rules('JENIS', 'JENIS', 'required');
        $this->form_validation->set_rules('DESKRIPSI', 'DESKRIPSI', 'required');
        $this->form_validation->set_rules('STATUS', 'STATUS', 'required');
        $this->form_validation->set_rules('HARGA', 'HARGA', 'required');
        $this->form_validation->set_rules('GAMBAR', 'GAMBAR', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'NAMABARANG' => $this->input->post('NAMABARANG'),
                'JENIS' => $this->input->post('JENIS'),
                'DESKRIPSI' => $this->input->post('DESKRIPSI'),
                'STATUS' => $this->input->post('STATUS'),
                'HARGA' => $this->input->post('HARGA'),
                'GAMBAR' => $this->input->post('GAMBAR'),
            );

            $barang_id = $this->Barang_model->add_barang($params);
            redirect('barang/index');
        } else {
            $data['_view'] = 'barang/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a barang
     */
    function edit($ID_BARANG)
    {
        // check if the barang exists before trying to edit it
        $data['barang'] = $this->Barang_model->get_barang($ID_BARANG);

        if (isset($data['barang']['ID_BARANG'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('NAMABARANG', 'NAMABARANG', 'required');
            $this->form_validation->set_rules('JENIS', 'JENIS', 'required');
            $this->form_validation->set_rules('DESKRIPSI', 'DESKRIPSI', 'required');
            $this->form_validation->set_rules('STATUS', 'STATUS', 'required');
            $this->form_validation->set_rules('HARGA', 'HARGA', 'required');
            $this->form_validation->set_rules('GAMBAR', 'GAMBAR', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'NAMABARANG' => $this->input->post('NAMABARANG'),
                    'JENIS' => $this->input->post('JENIS'),
                    'DESKRIPSI' => $this->input->post('DESKRIPSI'),
                    'STATUS' => $this->input->post('STATUS'),
                    'HARGA' => $this->input->post('HARGA'),
                    'GAMBAR' => $this->input->post('GAMBAR'),
                );

                $this->Barang_model->update_barang($ID_BARANG, $params);
                redirect('barang/index');
            } else {
                $data['_view'] = 'barang/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The barang you are trying to edit does not exist.');
    }

    /*
     * Deleting barang
     */
    function remove($ID_BARANG)
    {
        $barang = $this->Barang_model->get_barang($ID_BARANG);

        // check if the barang exists before trying to delete it
        if (isset($barang['ID_BARANG'])) {
            $this->Barang_model->delete_barang($ID_BARANG);
            redirect('barang/index');
        } else
            show_error('The barang you are trying to delete does not exist.');
    }
}
