<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sewaan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sewaan_model');
    } 

    /*
     * Listing of sewaan
     */
    function index()
    {
        $data['sewaan'] = $this->Sewaan_model->get_all_sewaan();
        
        $data['_view'] = 'sewaan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sewaan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ID_BARANG' => $this->input->post('ID_BARANG'),
				'ID_USER' => $this->input->post('ID_USER'),
				'TARIF' => $this->input->post('TARIF'),
				'DURASI_SEWA' => $this->input->post('DURASI_SEWA'),
				'STATUS' => $this->input->post('STATUS'),
            );
            
            $sewaan_id = $this->Sewaan_model->add_sewaan($params);
            redirect('sewaan/index');
        }
        else
        {            
            $data['_view'] = 'sewaan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sewaan
     */
    function edit($ID_SEWAAN)
    {   
        // check if the sewaan exists before trying to edit it
        $data['sewaan'] = $this->Sewaan_model->get_sewaan($ID_SEWAAN);
        
        if(isset($data['sewaan']['ID_SEWAAN']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ID_BARANG' => $this->input->post('ID_BARANG'),
					'ID_USER' => $this->input->post('ID_USER'),
					'TARIF' => $this->input->post('TARIF'),
					'DURASI_SEWA' => $this->input->post('DURASI_SEWA'),
					'STATUS' => $this->input->post('STATUS'),
                );

                $this->Sewaan_model->update_sewaan($ID_SEWAAN,$params);            
                redirect('sewaan/index');
            }
            else
            {
                $data['_view'] = 'sewaan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sewaan you are trying to edit does not exist.');
    } 

    /*
     * Deleting sewaan
     */
    function remove($ID_SEWAAN)
    {
        $sewaan = $this->Sewaan_model->get_sewaan($ID_SEWAAN);

        // check if the sewaan exists before trying to delete it
        if(isset($sewaan['ID_SEWAAN']))
        {
            $this->Sewaan_model->delete_sewaan($ID_SEWAAN);
            redirect('sewaan/index');
        }
        else
            show_error('The sewaan you are trying to delete does not exist.');
    }
    
}
