<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sewakan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //$this->load->model('Sewaan_model');
    }

    /*
     * Listing of sewaan
     */
    function index()
    {
        //$data['sewaan'] = $this->Sewaan_model->get_all_sewaan();
        $data['title'] = 'Sewakan Barang';

        $this->load->view('templates/profile/header_profile', $data);
        $this->load->view('templates/profile/navbar_profile', $data);
        $this->load->view('profile/sewakan', $data);
        $this->load->view('templates/profile/footer_profile', $data);
    }
}
