<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transaksi_sewa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Transaksi_sewa_model');
    } 

    /*
     * Listing of transaksi_sewa
     */
    function index()
    {
        $data['transaksi_sewa'] = $this->Transaksi_sewa_model->get_all_transaksi_sewa();
        
        $data['_view'] = 'transaksi_sewa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new transaksi_sewa
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ID_SEWAAN' => $this->input->post('ID_SEWAAN'),
				'ID_USER' => $this->input->post('ID_USER'),
				'TGL_TRANSAKSI' => $this->input->post('TGL_TRANSAKSI'),
				'LAMA_SEWA' => $this->input->post('LAMA_SEWA'),
				'TOTAL_TARIF' => $this->input->post('TOTAL_TARIF'),
            );
            
            $transaksi_sewa_id = $this->Transaksi_sewa_model->add_transaksi_sewa($params);
            redirect('transaksi_sewa/index');
        }
        else
        {            
            $data['_view'] = 'transaksi_sewa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a transaksi_sewa
     */
    function edit($ID_TRAKSAKSI)
    {   
        // check if the transaksi_sewa exists before trying to edit it
        $data['transaksi_sewa'] = $this->Transaksi_sewa_model->get_transaksi_sewa($ID_TRAKSAKSI);
        
        if(isset($data['transaksi_sewa']['ID_TRAKSAKSI']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ID_SEWAAN' => $this->input->post('ID_SEWAAN'),
					'ID_USER' => $this->input->post('ID_USER'),
					'TGL_TRANSAKSI' => $this->input->post('TGL_TRANSAKSI'),
					'LAMA_SEWA' => $this->input->post('LAMA_SEWA'),
					'TOTAL_TARIF' => $this->input->post('TOTAL_TARIF'),
                );

                $this->Transaksi_sewa_model->update_transaksi_sewa($ID_TRAKSAKSI,$params);            
                redirect('transaksi_sewa/index');
            }
            else
            {
                $data['_view'] = 'transaksi_sewa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The transaksi_sewa you are trying to edit does not exist.');
    } 

    /*
     * Deleting transaksi_sewa
     */
    function remove($ID_TRAKSAKSI)
    {
        $transaksi_sewa = $this->Transaksi_sewa_model->get_transaksi_sewa($ID_TRAKSAKSI);

        // check if the transaksi_sewa exists before trying to delete it
        if(isset($transaksi_sewa['ID_TRAKSAKSI']))
        {
            $this->Transaksi_sewa_model->delete_transaksi_sewa($ID_TRAKSAKSI);
            redirect('transaksi_sewa/index');
        }
        else
            show_error('The transaksi_sewa you are trying to delete does not exist.');
    }
    
}
