<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of user
     */
    function index()
    {
        $data['user'] = $this->User_model->get_all_user();
        
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'USERNAME' => $this->input->post('USERNAME'),
				'PASSWORD' => $this->input->post('PASSWORD'),
				'EMAIL' => $this->input->post('EMAIL'),
				'ROLE' => $this->input->post('ROLE'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($ID_USER)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($ID_USER);
        
        if(isset($data['user']['ID_USER']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'USERNAME' => $this->input->post('USERNAME'),
					'PASSWORD' => $this->input->post('PASSWORD'),
					'EMAIL' => $this->input->post('EMAIL'),
					'ROLE' => $this->input->post('ROLE'),
                );

                $this->User_model->update_user($ID_USER,$params);            
                redirect('user/index');
            }
            else
            {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($ID_USER)
    {
        $user = $this->User_model->get_user($ID_USER);

        // check if the user exists before trying to delete it
        if(isset($user['ID_USER']))
        {
            $this->User_model->delete_user($ID_USER);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
