<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get barang by ID_BARANG
     */
    function get_barang($ID_BARANG)
    {
        return $this->db->get_where('BARANG',array('ID_BARANG'=>$ID_BARANG))->row_array();
    }
        
    /*
     * Get all barang
     */
    function get_all_barang()
    {
        $this->db->order_by('ID_BARANG', 'desc');
        return $this->db->get('BARANG')->result_array();
    }
        
    /*
     * function to add new barang
     */
    function add_barang($params)
    {
        $this->db->insert('BARANG',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update barang
     */
    function update_barang($ID_BARANG,$params)
    {
        $this->db->where('ID_BARANG',$ID_BARANG);
        return $this->db->update('BARANG',$params);
    }
    
    /*
     * function to delete barang
     */
    function delete_barang($ID_BARANG)
    {
        return $this->db->delete('BARANG',array('ID_BARANG'=>$ID_BARANG));
    }
}
