<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sewakan_model extends CI_Model
{
    function get_all_barang_sewaan_by_user($ID_USER)
    {

        return $this->db->get_where('BARANG', array('ID_USER' => $ID_USER))->result_array();
    }
}
