<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Transaksi_sewa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get transaksi_sewa by ID_TRAKSAKSI
     */
    function get_transaksi_sewa($ID_TRAKSAKSI)
    {
        return $this->db->get_where('transaksi_sewa', array('ID_TRAKSAKSI' => $ID_TRAKSAKSI))->row_array();
    }

    function get_transaksi_sewa_by_user($ID_USER)
    {
        // $results = array();
        // $query = $this->db->query("SELECT * FROM `transaksi_sewa`, `sewaan`, `barang` WHERE transaksi_sewa.ID_SEWAAN = sewaan.ID_SEWAAN AND sewaan.ID_BARANG = barang.ID_BARANG AND barang.ID_USER = '$ID_USER'");

        // if ($query->num_rows() > 0) {
        //     $results = $query->row_array();  
        // }
        // return $results;

        return $this->db->query("SELECT * FROM `transaksi_sewa`, `sewaan`, `barang` WHERE transaksi_sewa.ID_SEWAAN = sewaan.ID_SEWAAN AND sewaan.ID_BARANG = barang.ID_BARANG AND barang.ID_USER = '$ID_USER'")->result_array();
    }

    /*
     * Get all transaksi_sewa
     */
    function get_all_transaksi_sewa()
    {
        $this->db->order_by('ID_TRAKSAKSI', 'desc');
        return $this->db->get('transaksi_sewa')->result_array();
    }

    /*
     * function to add new transaksi_sewa
     */
    function add_transaksi_sewa($params)
    {
        $this->db->insert('transaksi_sewa', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update transaksi_sewa
     */
    function update_transaksi_sewa($ID_TRAKSAKSI, $params)
    {
        $this->db->where('ID_TRAKSAKSI', $ID_TRAKSAKSI);
        return $this->db->update('transaksi_sewa', $params);
    }

    /*
     * function to delete transaksi_sewa
     */
    function delete_transaksi_sewa($ID_TRAKSAKSI)
    {
        return $this->db->delete('transaksi_sewa', array('ID_TRAKSAKSI' => $ID_TRAKSAKSI));
    }
}
