<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_detail by ID_DETAIL_USER
     */
    function get_user_detail($ID_DETAIL_USER)
    {
        return $this->db->get_where('USER_DETAIL',array('ID_DETAIL_USER'=>$ID_DETAIL_USER))->row_array();
    }
        
    /*
     * Get all user_detail
     */
    function get_all_user_detail()
    {
        $this->db->order_by('ID_DETAIL_USER', 'desc');
        return $this->db->get('USER_DETAIL')->result_array();
    }
        
    /*
     * function to add new user_detail
     */
    function add_user_detail($params)
    {
        $this->db->insert('USER_DETAIL',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_detail
     */
    function update_user_detail($ID_DETAIL_USER,$params)
    {
        $this->db->where('ID_DETAIL_USER',$ID_DETAIL_USER);
        return $this->db->update('USER_DETAIL',$params);
    }
    
    /*
     * function to delete user_detail
     */
    function delete_user_detail($ID_DETAIL_USER)
    {
        return $this->db->delete('USER_DETAIL',array('ID_DETAIL_USER'=>$ID_DETAIL_USER));
    }
}
