<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by ID_USER
     */
    function get_user($ID_USER)
    {
        return $this->db->get_where('user',array('ID_USER'=>$ID_USER))->row_array();
    }
        
    /*
     * Get all user
     */
    function get_all_user()
    {
        $this->db->order_by('ID_USER', 'desc');
        return $this->db->get('user')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('user',$params);
        return $this->db->insert();
    }
    
    /*
     * function to update user
     */
    function update_user($ID_USER,$params)
    {
        $this->db->where('ID_USER',$ID_USER);
        return $this->db->update('user',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($ID_USER)
    {
        return $this->db->delete('user',array('ID_USER'=>$ID_USER));
    }
}
